### ISSUE TITLE
Doubt how to use.

### ISSUE THREAD

**Issue by dcorrea777** [lcobucci/kafka#259]
Hi @lcobucci 

Where I work, we use kafka with some other languages.
In the case of php, I've already used this library https://github.com/arnaud-lb/php-rdkafka

But it's been some time since I saw this library, but until today I haven't understood how to use it.
I have this doubt because I didn't see any Consumer/Producer class.

Do you have any example or code snippets?

**Comment by lcobucci** [comment]
Hey @danilocorrea87 :wave: 

There's no example of how to use it yet because I haven't implemented the necessary features :grimacing:
The issues in [v0.1.0](https://github.com/lcobucci/kafka/milestone/1) are my first step towards having something working.

The thing is that life happened and I haven't been able to put much work into this lib. I do have plans to continue.

Closing it here :+1:

**Comment by dcorrea777** [comment]
Nice,

If you want to share some ideas I'm interested in helping  ;D

**Comment by lcobucci** [comment]
Hey @danilocorrea87!
Good to hear you want to help 😄 

I'm re-organising my thoughts and all... it's been a while since I was coding the first lines for this lib.
The [first milestone](https://github.com/lcobucci/kafka/milestone/1) is planned to be all about producing messages. Newer Kafka versions shipped some big changes to the protocol, which must be implemented properly here.
